- name: install build-essential
  apt:
    name: build-essential

- name: install pip
  apt:
    name: python3-pip

# Top-like tool for container metrics
- name: Download ctop binary
  get_url:
    url: https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64
    dest: /usr/local/bin/ctop
    mode: '0755'

- name: Make ctop executable
  file:
    path: /usr/local/bin/ctop
    mode: '0755'
    state: file
