- name: Create Jellyseerr config directory
  file:
    path: /services/jellyseerr/config
    state: directory
    recurse: true
  become: true
  register: jellyseer_config_dir

- name: Copy Jellyseerr icon
  copy:
    src: ../files/icon.svg
    dest: /services/homepage/icons/jellyseerr.svg
    owner: ant
    group: ant
    mode: '0644'
  become: true

- name: Create Jellyseerr container
  docker_container:
    name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart_policy: unless-stopped
    ports:
      - 5055:5055
    env:
      LOG_LEVEL: debug
      TZ: America/New_York
    log_driver: json-file
    log_options:
      max-file: "10"
      max-size: 200k
    volumes:
      - "{{ jellyseer_config_dir.path }}:/app/config"
    labels:
      homepage.group: Media
      homepage.name: Jellyseerr
      homepage.icon: /icons/jellyseerr.svg
      homepage.href: http://hub.antcar:5055
  register: jellyseerr_container

- name: Restart Homepage
  shell: docker restart homepage
  become: true
  when: jellyseerr_container is changed
