- name: Copy new music to Navidrome
  become: true
  ansible.builtin.synchronize:
    src: ../new-music/
    dest: /root/music/
    recursive: true
    delete: false
    rsync_opts:
      - "-v"

- name: Restart Navidrome
  become: true
  ansible.builtin.shell: docker compose restart navidrome
  args:
    chdir: /root/
  when: ansible_facts['synchronize'] is changed

