- name: copy new music to navidrome
  become: true
  ansible.builtin.synchronize:
    src: ../new-music/
    dest: /root/music/
    recursive: true
    delete: false
  notify: restart navidrome

# trigger navidrome restart now rather than at the end of the play
- meta: flush_handlers
