- name: Template Homepage config files
  template:
    src: ../files/{{ item }}.yaml
    dest: /var/lib/docker/volumes/root_homepage-config/_data/{{ item }}.yaml
  become: true
  with_items: 
    - bookmarks
    - docker
    - services
    - widgets
