- name: Ensure dirs exist
  file:
    path: /services/homepage/{{ item }}
    state: directory
  become: true
  with_items: 
    - config
    - icons

- name: Template Homepage config files
  template:
    src: ../files/{{ item }}.yaml
    dest: /services/homepage/config/{{ item }}.yaml
  become: true
  with_items: 
    - bookmarks
    - docker
    - services
    - widgets
