- name: Install NFS server packages
  apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present

- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /media
    - /services

- name: Configure NFS exports
  blockinfile:
    path: /etc/exports
    block: |
      /media    192.168.1.0/24(rw,sync,no_subtree_check)
      /services 192.168.1.0/24(rw,sync,no_subtree_check)
    state: present

- name: Restart NFS server to apply changes
  service:
    name: nfs-kernel-server
    state: restarted
    enabled: true

- name: Open NFS ports on the firewall
  ufw:
    rule: allow
    port: '2049'
    proto: tcp
