# ---
# # For configuration options and examples, please see:
# # https://gethomepage.dev/latest/configs/services

- Networking:
    - pfSense:
        href: https://pfsense.home.arpa
        icon: https://www.itandgeneral.com/wp-content/uploads/2023/11/pfsense-logo-square.png
    - Living Room WAP:
        href: https://usopp01.antcar.casa
        icon: https://static.tp-link.com/upload/image-line/EAP650_UN_1.0_large_20230821091901o.png
    - Closet Switch:
        href: https://nami01.antcar.casa
        icon: https://static.tp-link.com/upload/image-line/SG2016P_UN_1.2_01_large_20240207020458g.jpg
    - PiHole (Robin):
        href: https://robin.antcar.casa/admin
        icon: https://raw.githubusercontent.com/loganmarchione/homelab-svg-assets/main/assets/pihole.svg
    - PiHole (Olvia):
        href: https://olvia.antcar.casa/admin
        icon: https://raw.githubusercontent.com/loganmarchione/homelab-svg-assets/main/assets/pihole.svg

- Data:
    - TrueNAS:
        href: https://nas.antcar.casa
        icon: https://raw.githubusercontent.com/loganmarchione/homelab-svg-assets/main/assets/truenas-scale.svg
# - Media:
#     - Jellyfin:
#         href: https://jellyfin.antcar.casa
#         icon: si-#00A4DC
#     - Navidrome:
#         href: https://music.antcar.casa
#         icon: mdi-F075A
#     - Prowlarr:
#         href: http://hub.antcar:9696
#         icon: si-#CD792C
#     - Sonarr: 
#         href: http://hub.antcar:8989
#         icon: si-#2596BE
#     - Bazarr:
#         href: http://hub.antcar:6767
#         icon: mdi-F0A16
#     - SabNZBD:
#         href: http://192.168.1.4:8990
#         icon: mdi-F1462

# - Home Automation:
#     - Home Assistant:
#         href: https://ha.antcar.casa
#         icon: si-#18BCF2
#     - Zigbee2MQTT:
#         href: http://hub.antcar:8080
#         icon: si-#EB0443
#     - ZWave-JS-UI:
#         href: http://hub.antcar:8091
#         icon: mdi-F0AEA
#     - ESPHome:
#         href: http://hub.antcar:6052
#         icon: si-#000000
# - Observability:
#     - Dozzle:
#         href: http://hub.antcar:9999
#         icon: mdi-F1085
#     - Speedtest:
#         href: http://hub.antcar:8765
#         icon: si-#141526
