- name: Create service config directory
  with_items: "{{ media_services }}"
  file:
    path: /services/{{ item }}/config
    state: directory
    recurse: true
  become: true

- name: Copy service icon
  with_items: "{{ media_services }}"
  copy:
    src: ../files/{{ item }}.svg
    dest: /services/homepage/icons/{{ item }}.svg
    owner: {{ default_user }}
    group: {{ default_user }}
    mode: '0644'
  become: true

- name: Create service container
  with_items: "{{ media_services }}"
  docker_container:
    name: {{ item }}
    image: "{{ item.image }}:{{ item.version }}"
    restart_policy: unless-stopped
    ports: {{ item.ports }}
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: {{ time_zone }}
    log_driver: json-file
    log_options:
      max-file: "10"
      max-size: 200k
    volumes:
      - "/services/{{ item }}/config:/config"
      - /media/{{ item.type }}:/media
      - /media/downloads:/downloads
    labels:
      homepage.group: Media Backend
      homepage.name: {{ item | capitalize }}
      homepage.icon: /icons/{{ item }}.svg
      homepage.href: https://{{ item }}.antcar.casa
  register: media_container

# Create nginx proxy host

# Create DNS record

- name: Restart Homepage
  shell: docker restart homepage
  become: true
  when: media_container is changed
