# - name: debug vars
#   debug:
#     var: "{{ vars }}"

- name: "Create config directory"
  file:
    path: "/services/{{ item.name }}/config"
    state: directory
    recurse: true
  become: true
  loop: "{{ media_services }}"

- name: "Copy icon"
  copy:
    src: "../files/{{ item.name }}.svg"
    dest: "/services/homepage/icons/{{ item.name }}.svg"
    owner: "{{ default_user_uid }}"
    group: "{{ default_user_gid }}"
    mode: '0644'
  become: true
  loop: "{{ media_services }}"
  register: media_icon

# TODO: Create nginx proxy host

# TODO: Create DNS record

- name: Restart Homepage
  shell: docker restart homepage
  become: true
  when: media_icon is changed
