- name: Set secrets
  set_fact:
    bw_secrets: "{{ hostvars.localhost }}"

- name: Create services directory
  file:
    path: /services
    state: directory

- name: Create directories for services
  file:
    path: "/services/{{ item }}"
    state: directory
  with_items:
    - janitorr/config
    - unpackerr/config

- name: Template Janitorr config
  template:
    src: ../files/janitorr.yml.j2
    dest: /services/janitorr/config/application.yml
  when: bw_secrets is defined

- name: Template Unpackerr config
  template:
    src: ../files/unpackerr.conf.j2
    dest: /services/unpackerr/config/unpackerr.conf
  when: bw_secrets is defined

- name: Template the Docker Compose file
  template:
    src: ../files/docker-compose.yml.j2
    dest: /services/docker-compose.yml
  become: true
  when: bw_secrets is defined

- name: Pull new images
  command: docker compose pull 
  args:
    chdir: /services/
  become: true

- name: Run Docker Compose
  command: docker compose up -d --remove-orphans
  args:
    chdir: /services/
  become: true
