- name: Set facts
  set_fact:
    bw_secrets: "{{ hostvars.localhost.bw_secrets }}"

- name: Create services directory
  file:
    path: /services
    state: directory

- name: Set each secret as a variable
  set_fact:
    "{{ item.name }}": "{{ item.value }}"
  loop: "{{ bw_secrets }}"
  no_log: true

- name: Template the Docker Compose file
  template:
    src: ../files/docker-compose.yml.j2
    dest: /root/docker-compose.yml
  become: true
  when: bw_secrets is defined

- name: Run Docker Compose
  command: docker compose up -d --remove-orphans
  args:
    chdir: /root/
  become: true
