- name: Set secrets
  set_fact:
    bw_secrets: "{{ hostvars.localhost }}"

- name: Create services directory
  file:
    path: /services
    state: directory

- name: Template the Docker Compose file
  template:
    src: ../files/docker-compose.yml.j2
    dest: /root/docker-compose.yml
  become: true
  when: bw_secrets is defined

- name: Pull new images
  command: docker compose pull 
  args:
    chdir: /root/
  become: true

- name: Run Docker Compose
  command: docker compose up -d --remove-orphans
  args:
    chdir: /root/
  become: true
